@startuml

actor Client as C

control ForecastController as FC

database WeatherBatchResultObject as SSDAO

C -> FC :GET /clima?dia=566

FC -> SSDAO : day(566)

SSDAO --> FC :weatherForecast

FC --> C : {"dia":"566", "clima":"lluvia"}


@enduml